=== api-evangelist/weaviate/json-schema/weaviate-replicationreplicatedetailsreplicaresponse-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/ReplicationReplicateDetailsReplicaResponse",
  "title": "ReplicationReplicateDetailsReplicaResponse",
  "description": "Provides a comprehensive overview of a specific replication operation, detailing its unique ID, the involved collection, shard, source and target nodes, transfer type, current status, and optionally, its status history.",
  "required": [
    "id",
    "shard",
    "sourceNode",
    "targetNode",
    "collection",
    "status",
    "type"
  ],
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "The unique identifier (ID) of this specific replication operation."
    },
    "shard": {
      "type": "string",
      "description": "The name of the shard involved in this replication operation."
    },
    "collection": {
      "type": "string",
      "description": "The name of the collection to which the shard being replicated belongs."
    },
    "sourceNode": {
      "type": "string",
      "description": "The identifier of the node from which the replica is being moved or copied (the source node)."
    },
    "targetNode": {
      "type": "string",
      "description": "The identifier of the node to which the replica is being moved or copied (the target node)."
    },
    "type": {
      "type": "string",
      "description": "Indicates whether the operation is a `COPY` (source replica remains) or a `MOVE` (source replica is removed after successful transfer).",
      "enum": [
        "COPY",
        "MOVE"
      ]
    },
    "uncancelable": {
      "type": "boolean",
      "description": "Whether the replica operation can't be cancelled."
    },
    "scheduledForCancel": {
      "type": "boolean",
      "description": "Whether the replica operation is scheduled for cancellation."
    },
    "scheduledForDelete": {
      "type": "boolean",
      "description": "Whether the replica operation is scheduled for deletion."
    },
    "status": {
      "$ref": "#/components/schemas/ReplicationReplicateDetailsReplicaStatus"
    },
    "statusHistory": {
      "type": "array",
      "description": "An array detailing the historical sequence of statuses the replication operation has transitioned through, if requested and available.",
      "items": {
        "$ref": "#/components/schemas/ReplicationReplicateDetailsReplicaStatus"
      }
    },
    "whenStartedUnixMs": {
      "type": "integer",
      "format": "int64",
      "description": "The UNIX timestamp in ms when the replication operation was initiated. This is an approximate time and so should not be used for precise timing."
    }
  }
}

=== api-evangelist/weaviate/examples/weaviate-replication-replicate-details-replica-response-example.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "shard": "example-wtfyjike",
  "collection": "example-xpojefwh",
  "sourceNode": "example-gjczrdxd",
  "targetNode": "example-qhptlfkl",
  "type": "COPY",
  "uncancelable": true,
  "scheduledForCancel": true,
  "scheduledForDelete": true,
  "status": {
    "id": "example-id"
  },
  "statusHistory": [
    {
      "id": "example-id"
    }
  ],
  "whenStartedUnixMs": 47
}
