=== api-evangelist/weaviate/json-schema/weaviate-statistics-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api-evangelist.github.io/weaviate/json-schema/weaviate-statistics-schema.json",
  "title": "Statistics",
  "description": "The definition of node statistics.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the node."
    },
    "status": {
      "type": "string",
      "description": "Node's status.",
      "enum": [
        "HEALTHY",
        "UNHEALTHY",
        "UNAVAILABLE",
        "TIMEOUT"
      ],
      "default": "HEALTHY"
    },
    "bootstrapped": {
      "type": "boolean"
    },
    "dbLoaded": {
      "type": "boolean"
    },
    "initialLastAppliedIndex": {
      "type": "number",
      "format": "uint64"
    },
    "lastAppliedIndex": {
      "type": "number"
    },
    "isVoter": {
      "type": "boolean"
    },
    "leaderId": {
      "type": "object"
    },
    "leaderAddress": {
      "type": "object"
    },
    "open": {
      "type": "boolean"
    },
    "ready": {
      "type": "boolean"
    },
    "candidates": {
      "type": "object"
    },
    "raft": {
      "$ref": "#/components/schemas/RaftStatistics"
    }
  }
}

=== api-evangelist/weaviate/examples/weaviate-statistics-example.json
{
  "name": "example-xtnbixtu",
  "status": "HEALTHY",
  "bootstrapped": true,
  "dbLoaded": true,
  "initialLastAppliedIndex": 25.16,
  "lastAppliedIndex": 7.31,
  "isVoter": true,
  "leaderId": {},
  "leaderAddress": {},
  "open": true,
  "ready": true,
  "candidates": {},
  "raft": {
    "id": "example-id"
  }
}
